### ISSUE TITLE
Parse error: syntax error, unexpected '[' in Tabber.php on line 16

### ISSUE THREAD

**Issue by hdurre** [Alexia/Tabber#2]
Hi,
I have an error, when I install the extension:
Parse error: syntax error, unexpected '[' in /var/www/mediawiki-1.24.0/extensions/Tabber/Tabber.php on line 16

I reproduced this with this minimal configuration:
MediaWiki	1.24.0
PHP	5.3.3 (apache2handler
MySQL	5.1.73
&
Semantic MediaWiki	2.0
Validator	2.0.4
DataValues	1.0
DataValues Common	0.2.3
DataValues Validators	0.1.2
DataValuesInterfaces	0.1.4

Do you have a work around to run this extension ?
Regards
henri

**Comment by Alexia** [comment]
PHP 5.4 and higher is supported is only by Tabber.

**Comment by Telshin** [comment]
I'll be working on a PHP 5.3 compatible branch.

**Comment by Alexia** [comment]
@Telshin has made a PHP 5.3 compatibility branch and a release is available under releases.
https://github.com/Alexia/Tabber/releases
