### ISSUE TITLE
Implementing required once

### ISSUE THREAD

**Issue by Clemonde** [Alexia/Tabber#7]
Hi Alexia,

after I uploaded "Tabber" into the extensions directory, I put 

require_once "$IP/extensions/Tabber/Tabber.php";

at the bottom of localsettings.php 

but if I reload my wiki after that, there is only a blank screen.

http://under-control.wikii.net/wiki/Main_Page

I can reproduce this issue if needed

Kind regards, 

Clemonde

**Comment by noahm** [comment]
Hi Clemonade,
Double check that your server is running at least PHP 5.4 and if not you need to download the version from the `compat` branch. If that doesn't turn out to be the problem, then you will have to enable PHP error display on your server to see what the problem is.

**Comment by noahm** [comment]
Actually, a quick glance at [your Special:Version](http://under-control.wikii.net/wiki/Special:Version) tells me that you are using PHP 5.3, so if you simply grab [the latest compat version](https://github.com/Alexia/Tabber/releases/tag/v2.3-compat), then you should be all set.

**Comment by Clemonde** [comment]
thanks for the quick reply ... I'll try it out ;)
