### ISSUE TITLE
"Notice: Undefined variable" with DynamicPageList (third party)

### ISSUE THREAD

**Issue by bogota** [Alexia/Tabber#8]
I get the PHP notice message "Notice: Undefined variable: htmlTabs in (path to htdocs)\mediawiki\extensions\Tabber\Tabber.hooks.php on line 42" when and only when one or more DynamicPageList (third party) http://www.mediawiki.org/wiki/Extension:DynamicPageList_(third-party) queries are placed inside Tabber tabs like:

```
<tabber>
tab1={{#dpl:|namespace=}}
</tabber>
```

Queries of similar style by other extensions (SubPageList, Semantic MediaWiki) works well inside Tabber tabs without emitting this kind of warning.

**Comment by Alexia** [comment]
Looks like an uninitialized variable.  I will look at in the morning and get it taken care of.

**Comment by Alexia** [comment]
If you download the latest development break it includes the fix for this issue.

https://github.com/Alexia/Tabber/commit/67229ccf73f25838fcdaf17c513722454e2e6ea5

**Comment by bogota** [comment]
Checked out the master branch and have verified no more notices emerged. Thank you much.
